name: deploy-ingestion-pipeline

on:
  workflow_dispatch:
jobs:
  get-config:
    uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
    with:
      file_name: config-infra-prod.yml

  register-dataset:
    needs: get-config
    uses: ./.github/workflows/register-dataset.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      name: coco-data
      data_file: mlops/azureml/ingestion/data.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}

  create-compute:
    needs: [get-config, register-dataset]
    uses: ./.github/workflows/create-compute.yml
    with:
      cluster_name: cpu-cluster
      size: Standard_DS3_v2
      min_instances: 0
      max_instances: 4
      cluster_tier: low_priority
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}

  run-pipeline:
    needs: [get-config, create-compute, register-dataset]
    uses: ./.github/workflows/run-pipeline.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      parameters-file: mlops/azureml/ingestion/pipeline.yml
      job-name: test
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
